<%= ENV['ZABBIX_AGENT1_FQDN'] %>:
  fqdn: <%= ENV['ZABBIX_AGENT1_FQDN'] %>
  interfaces:
    eth0:
      type: 1
      main: 1
      ip: <%= ENV['ZABBIX_AGENT1_IP'] %>
      dns: <%= ENV['ZABBIX_AGENT1_FQDN'] %>
      port: 10050
      useip: 1
  groups:
    groupid1: "Linux servers"
  templates:
    template1: "My_Template_App_HTTP_Service"
    template2: "My_Template_App_HTTPS_Service"
    template3: "My_Template_App_NTP_Service"
    template4: "My_Template_App_SMTP_Service"
    template5: "My_Template_App_Zabbix_Agent"
    template6: "My_Template_ICMP_Ping"
    template7: "My_Template_OS_Linux"
    template8: "My_Template_SSH_Service"
    template9: "My_Template_App_Chef_Server"
    template10: "My_Template_App_Chef_Client"

<%= ENV['ZABBIX_SERVER_FQDN'] %>:
  fqdn: <%= ENV['ZABBIX_SERVER_FQDN'] %>
  interfaces:
    eth0:
      type: 1
      main: 1
      ip: "127.0.0.1"
      dns: <%= ENV['ZABBIX_SERVER_FQDN'] %>
      port: 10050
      useip: 1
  groups:
    groupid1: "Linux servers"
  templates:
    template1: "My_Template_App_HTTP_Service"
    template2: "My_Template_App_HTTPS_Service"
    template3: "My_Template_App_MySQL"
    template4: "My_Template_App_NTP_Service"
    template5: "My_Template_App_SMTP_Service"
    template6: "My_Template_App_Zabbix_Agent"
    template7: "My_Template_App_Zabbix_Server"
    template8: "My_Template_ICMP_Ping"
    template9: "My_Template_OS_Linux"
    template10: "My_Template_SSH_Service"
    template11: "My_Template_App_Chef_Client"

