name: "My_Template_App_NTP_Service"
groups:
  - "Templates"
applications:
  - "NTP service"
items:
  item1:
    name: "NTP service is running"
    key_: "net.tcp.service[ntp]"
    type: 0
    value_type: 3
    delay: 60
    trapper_hosts: ""
    formula: 1
    valuemapid: 1
triggers:
  trigger1:
    description: "NTP service is down on {HOST.NAME}"
    expression: "{My_Template_App_NTP_Service:net.tcp.service[ntp].max(#3)}=0"
    priority: 3


