name: "My_Template_App_HTTP_Service"
groups:
  - "Templates"
applications:
  - "HTTP service"
items:
  item1:
    name: "HTTP service is running"
    key_: "net.tcp.service[http]"
    type: 0
    value_type: 3
    delay: 60
    trapper_hosts: ""
    formula: 1
    valuemapid: 1
triggers:
  trigger1:
    description: "HTTP service is down on {HOST.NAME}"
    expression: "{My_Template_App_HTTP_Service:net.tcp.service[http].max(#3)}=0"
    priority: 3

