name: "My_Template_App_Chef_Client"
groups:
  - "Templates"
applications:
  - "Chef client"
items:
  item1:
    name: "Chef client is running"
    key_: "proc.num[chef-client]"
    type: 0
    value_type: 3
    delay: 60
    trapper_hosts: ""
    formula: 1
    valuemapid: 1
triggers:
  trigger1:
    description: "Chef client is down on {HOST.NAME}"
    expression: "{My_Template_App_Chef_Client:proc.num[chef-client].max(#3)}=0"
    priority: 3



